# Specify an alternative configuration file.
#
# By default, tmux loads the system configuration file
# from /etc/tmux.conf, if present, then looks for a user
# configuration file at ~/.tmux.conf.
#
# The configuration file is a set of tmux commands which
# are executed in sequence when the server is first started.
#
# tmux loads configuration files once when the server
# process has started.
#
# The source-file command may be used to load a file later.
#
# tmux shows any error messages from commands in
# configuration files in the first session created, and
# continues to process the rest of the configuration file.

# To enable scrolling, clicking, and resizing
set -g mouse on

# By default, tmux keeps the previous 2000 lines of window history.
# Increase it to 5000 lines
set-option -g history-limit 5000

# Numbering Windows and Panes
#
# Recall that tmux windows and panes are 0-based.
# I find them not really intuitive.
# Set your first windows and panes to start with 1.
set -g base-index 1
setw -g pane-base-index 1

# Change default window numbering behavior after closing.
set -g renumber-windows on

# Press "Prefix + |", tmux does a vertical split and press
# "Prefix + -", tmux does a horizontal split.
bind | split-window -hc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# Allow to press either the uppercased version of that
# key to get the vertical / horizontal splits.
bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"

bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"

# Preserve the path in the new window
bind c new-window -c "#{pane_current_path}"

# Tmux Resurrect
# Restore tmux environment after system restart.
run-shell ~/.config/tmux/resurrect/resurrect.tmux

# Tmux Continuum
#   1) continuous saving of tmux environment
#   2) automatic tmux start when computer/server is turned on
#   3) automatic restore when tmux is started
run-shell ~/.config/tmux/continuum/continuum.tmux
